### ISSUE TITLE
Invisible past events

### ISSUE THREAD

**Issue by MarkShek01** [Exoceus/cloak#10] opened 2024-01-12 14:38 UTC
I primarily use the monthly view as my starting point. I can't see text for past events unless they're marked as "all day" events (see screenshot).  Not sure if this was intended, but I'd prefer to be able to see the text for them, even if in a minimally contrasted gray color?

![image](https://github.com/Exoceus/cloak/assets/156444618/b0b1b5b6-f1df-4fd8-b6b2-3d6af53f52b5)

**Comment by tsnavi** [comment] 2024-02-27 00:32
Same issue here ++

Left is past, right is current day
![image](https://github.com/Exoceus/cloak/assets/145156860/9761fc6a-363b-405d-82a6-576bb63bd905)

**Comment by Exoceus** [comment] 2024-03-04 15:27
Hi @MarkShek01 and @tsnavil , Sorry for the late reply!

I have diagnosed this issue and it is due to the "Reduce the brightness of past events" option.
<img width="844" alt="image" src="https://github.com/Exoceus/cloak/assets/27310726/4353b0ce-a19e-4517-9ec7-200f72f8d37c">

I will push out a version to fix this within a week.

**Comment by tsnavi** [comment] 2024-03-04 17:07
Nice one! 😊

**Comment by Exoceus** [comment] 2024-03-13 00:41
@tsnavi @MarkShek01 A new version has been pushed. It should auto update on your machines in the coming days

**Comment by tsnavi** [comment] 2024-03-13 10:38
Amazing! Thanks Jatin 👍

**Comment by tsnavi** [comment] 2024-03-19 22:50
Jatin, thank you for the change. One minor tweak: the all-day events still show with white text on light bg

![image](https://github.com/Exoceus/cloak/assets/145156860/fb8d139d-6c2a-4667-8ddd-6db7d951991d)

**Comment by Exoceus** [comment] 2024-03-22 01:57
Good catch

**Comment by Exoceus** [comment] 2024-03-22 02:28
Fixed in v0.3.2 (should come out soon)

**Comment by tsnavi** [comment] 2024-03-22 09:35
Nice one :D

**Comment by tsnavi** [comment] 2024-03-22 18:00
@Exoceus Old issue is solved - however on first load this happens. Goes away if you go forward one week and then back again, but reproducible with ctrl+r: 
First load. Returns if ctrl+r:
![image](https://github.com/Exoceus/cloak/assets/145156860/29d6133b-80a5-4611-81fd-a7eb28c79efd)
Forward one week and back again:
![image](https://github.com/Exoceus/cloak/assets/145156860/c02e1617-79f3-44bc-8dd9-7d4db945a58b)

This also happens, if it helps you narrow down the cause:
![image](https://github.com/Exoceus/cloak/assets/145156860/a70d144d-0a6b-4056-81b2-2413ba8243ff)
![image](https://github.com/Exoceus/cloak/assets/145156860/90c8cf8d-fbac-4b0f-a1ba-f2362c035fb9)

**Comment by Exoceus** [comment] 2024-03-23 15:49
I'm not quite able to replicate. For me it works even if I reload and move back and forth

**Comment by Exoceus** [comment] 2024-03-23 15:49
I'll keep this issue as closed a create a new issue

**Closed as completed by Exoceus** 2024-03-23 15:49 UTC
Labels: bug

**Comment by Exoceus** [comment] 2024-03-23 15:53
I just realized, could you verify your extension version? This should be fixed in v0.3.3 (release yesterday)

**Comment by tsnavi** [comment] 2024-03-24 19:55
I am using 0.3.3 🤔
